### ISSUE TITLE
Debian 環境安裝問題

### ISSUE THREAD

**Issue by toro-du** [Yuchunchen/BuildYourOwnConferenceSystem#1]
您好我是linux 初心者，目前只有安裝jitsi-meet server 網站正常。
但要如何套用您的介面呢? 目前是使用Debian 10.3 
已經使用git clone 並cp -arv到相應的usr/share/jitsi-meet/ 下了
但在網站上還是預設英文版 調整語系也跟原本的一樣。
![image](https://user-images.githubusercontent.com/64185325/80452795-939f3280-8959-11ea-84a9-bc9f5cc23b8a.png)

**Comment by Yuchunchen** [comment]
> 您好我是linux 初心者，目前只有安裝jitsi-meet server 網站正常。
> 
> 但要如何套用您的介面呢? 目前是使用Debian 10.3 
> 
> 已經使用git clone 並cp -arv到相應的usr/share/jitsi-meet/ 下了
> 
> 但在網站上還是預設英文版 調整語系也跟原本的一樣。
> 
> ![image](https://user-images.githubusercontent.com/64185325/80452795-939f3280-8959-11ea-84a9-bc9f5cc23b8a.png)
> 
> 

恭喜已經成功完成server安裝！
您可以連結 https://hostname/meet_ym.html
進入畫面，請再試試看！
